### 抄袭 viper
run:
  timeout: 5m
  issues.exclude-dirs:
    - vendor # Go 依赖管理中常用的第三方包目录
    - third_party # 其他外部库目录（根据项目结构自定义）
    - external # 另一种外部代码存放目录

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - gci
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/HunDun0Ben/bs_server)
        - blank
        - dot
        - alias
      # 避免 import 之间出现注释，保持机器可读
      no-inline-comments: true
      no-prefix-comments: true
      # 按 sections 定义顺序排序
      custom-order: true
      # 推荐开启字母排序，使团队协作 diff 更少
      no-lex-order: false
    gocritic:
      # Enable multiple checks by tags. See "Tags" section in https://github.com/go-critic/go-critic#usage.
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - style
      disabled-checks:
        - importShadow
        - unnamedResult
